ci:
  autoupdate_schedule: monthly
repos:
  - repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
      - id: black
#  - repo: https://github.com/PyCQA/flake8
#    rev: 4.0.1
#    hooks:
#      - id: flake8
#        additional_dependencies:
#          - flake8-bugbear
#          - flake8-implicit-str-concat
#  - repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v4.0.1
#    hooks:
#      - id: fix-byte-order-marker
#      - id: trailing-whitespace
#      - id: end-of-file-fixer
